complete text, duration, midi, npy, wav and data_dir and left the data.sh to complish
SJTMusicTeam/Muskits pull request #5
Opened 2021-05-22 08:03 UTC by DrWelles

i may finish these 2days later

2021-05-23 00:35 UTC, ftshijt commented
please add corresponding package requirements at `setup.py` (e.g., miditoolkit)

2021-05-27 05:07 UTC, ftshijt requested changes

2021-05-27 05:07 UTC, ftshijt commented on egs/kiritan/local/prep_segments.py
> +        # # labels = hts.load(lab_path)
Please remove these lines with comments

2021-05-27 05:07 UTC, ftshijt commented on egs/kiritan/local/prep_segments.py
> +            # lab_path = path.replace("wav/", "lab/").replace(".wav", ".lab")
remove debug information

2021-05-27 05:07 UTC, ftshijt commented on egs/kiritan/local/prep_segments.py
> +    Window_size = 60 * 1e-3
This should be aligned with some arguments, the window size should not be fixed here (so as the window shift next line)

2021-05-27 05:07 UTC, ftshijt commented on egs/kiritan/local/prep_segments.py
> +            recording_id, path = line.split()
I don't think this is a robust function though. What if we have

utt1 "place_with_ space _/wav"

2021-05-27 05:07 UTC, ftshijt commented on egs/kiritan/local/prep_segments.py
> +            i = seg_id * Window_shift
window size and window shift, only 60ms for a segment?

2021-05-27 05:07 UTC, ftshijt commented on muskit/fileio/midi_scp.py
> +        # if self.normalize:
remove comments

2021-05-27 05:07 UTC, ftshijt commented on muskit/fileio/utils.py
> +if __name__ == '__main__':
move this part to test functions later (we do not have them yet)

2021-05-27 05:07 UTC, ftshijt commented
Please reflect on the comments and fix the conflict. Then I will merge it.

2021-05-31 15:47 UTC, DrWelles commented
well, it seems that it's quiet slow and may be faster....

2021-05-31 15:48 UTC, ftshijt requested changes

2021-05-31 15:48 UTC, ftshijt commented on setup.py
> +<<<<<<< Updated upstream
There seems some conflicts not fixed

2021-05-31 15:48 UTC, ftshijt commented on muskit/fileio/midi_scp.py
> +>>>>>>> Stashed changes
same for here

2021-05-31 15:48 UTC, ftshijt commented on muskit/fileio/read_text.py
> +<<<<<<< Updated upstream
Please check `<<<<<` to make sure no errors

2021-05-31 15:49 UTC, ftshijt commented
> well, it seems that it's quiet slow and may be faster....

Which part is slow? Format wav or preparing at the beginning?

2021-05-31 15:51 UTC, DrWelles commented
> > well, it seems that it's quiet slow and may be faster....
> 
> Which part is slow? Format wav or preparing at the beginning?

format wav&midi, the text and duration is fast enough

2021-06-01 01:24 UTC, ftshijt requested changes

2021-06-01 01:24 UTC, ftshijt commented on muskit/fileio/midi_scp.py
> +<<<<<<< Updated upstream
Because of the merge conflict, there remains such FIXME code, please fix them

2021-06-01 17:21 UTC, ftshijt commented
There are still some setting issues, I will follow this PR, so will not merge until I fix the issues

2021-06-13 14:45 UTC, merged