combine recipe
SJTMusicTeam/Muskits pull request #57
Opened 2022-01-23 12:22 UTC by DrWelles

2022-01-27 06:38 UTC, ftshijt commented on egs/combine_data/svs1/local/data.sh
> +for dataset in ${train_set} ${train_dev} ${recog_set}; do
Can you add some notes for users to better understand the stages?

2022-01-27 09:27 UTC, DrWelles commented on egs/combine_data/svs1/local/data.sh
> +for dataset in ${train_set} ${train_dev} ${recog_set}; do
Done

2022-01-27 15:55 UTC, ftshijt requested changes
Many important files are deleted! Please check them carefully before making a PR. This is super dangerous!!!

2022-01-27 15:55 UTC, ftshijt commented on egs/kiritan/svs1/run.sh
> +>>>>>>> fdfbfedc87702a68ec427f862ac398153d02d20d
Please fix the conflict...

2022-01-27 15:55 UTC, ftshijt commented on egs/ofuton_p_utagoe_db/svs1/cmd.sh
> +<<<<<<< HEAD
same here

2022-01-28 03:37 UTC, ftshijt commented
THe makefile is still deleted, please recover it

2022-01-28 03:37 UTC, ftshijt commented
Also conflict exists

2022-01-28 03:42 UTC, ftshijt commented
Can you change the `activate_python.sh` into default version here https://github.com/SJTMusicTeam/Muskits/blob/9eda7fa8dd7a38976cf156a0e2a0175305a2a9dd/tools/activate_python.sh

2022-01-28 13:53 UTC, ftshijt commented on egs/combine_data/svs1/local/dataset_split.py
> +#!/usr/bin/env python3
ditto

2022-01-28 13:53 UTC, ftshijt commented on egs/combine_data/svs1/local/prep_segments.py
> +#!/usr/bin/env python3
ditto

2022-01-28 14:00 UTC, ftshijt commented
Can you also add a readme file or some explanation in the recipe, so that helps others to get start?

2022-01-30 04:17 UTC, merged